spotify:
    client_id: ENC[AES256_GCM,data:BFwvgvxwq5bQ/JAYywpIOLHXiwAdS2oX9EVMyyHkWEIq9nX4,iv:zXWyDbGNIK75rHvg0J4ZTLKPKjDwV5aG/5VytPLsoX8=,tag:8TBd9OZ8bYYXSnMMNHNMkg==,type:str]
    client_secret: ENC[AES256_GCM,data:Mt5I0Gk/C2OV8aSb+u8hloLmefMRDmPFDnC/MykzU5YArr0seFJYp9YCEME=,iv:FNGTtfbZYaNgzV/ebF0F+/rMHZ32mEQqVsWYt4Ur5LI=,tag:LVLlMzMNJHAs7hN/BMJO4A==,type:str]
    username: ENC[AES256_GCM,data:BAWRDJTFn76xqG2f6S7H5kD7FWsoAF+G7g==,iv:OCbTERmBbrq95XVsR2tWtUt/aYA8dCYB4yjFm7KCfbU=,tag:CLeVcbfnXWj0LvKICNsf1g==,type:str]
    password: ENC[AES256_GCM,data:PrjH/nTVIMPbuCw=,iv:FPiOnKsa1kQ1hoLZdQeudRCavSVM1g5cznCc6ScKds8=,tag:tqA0LdTyBoI6cNsGi2eyQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16p2a4vs2rhf4f80nf58lk0fqkh3vuapn6vlgnfcs5pscm2ekjvfqegqg4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN055b2FYWVgrVHFuQUZm
            Z2UybjFsdHVvNDRNcVR5T0ZqbEcvOWlzM0RRClc1bWdyK01iQ2ZtUWZsakZEMUtM
            S3g5U1FSMXBjakNOdTliMXBuR3RCTWsKLS0tIHZ1Ky9ncldyaktBSkQ1UjEvRWZV
            d3BEemtPOW5QQXJoZVZzM2FRWEJJamsKT6tPEDNEGm0A6xyU8jG9zWqbYWeUOmNO
            FgvsX/m1B1fxnhK3Pko+iJ22MifrXJQK24NrqEqS6dEuYDfxfBQE+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T07:47:52Z"
    mac: ENC[AES256_GCM,data:42Br0q9DaOQlcnmIjLHx/15jzqS9qt1F+jNDkbsO/qrLACiyO9wajtHZJDXdhb/ZKqhkPpWNxt/ZanmQUBPwEOvmLsoZCpEIIpdj9wgoYQG0W1cbMMUnhKmqTxYgAP2F2EezbIdpvtlXVfVe28GchzV7u9MX65fs07X6FvhGYCE=,iv:H/d0vkW7z/invP71II7cEgqcPL18AZ1bU0VA0kGbu7k=,tag:6reGWT8GLamyxGXif/7C8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
